import { Sparkles, Lightbulb, ListChecks, AlertTriangle, BookOpen } from "lucide-react";

/**
 * Robustly parses AI output:
 *  - object with summary/recommendations/etc
 *  - JSON string
 *  - plain text (treated as summary)
 */
function normalize(raw) {
  if (!raw) return null;
  let data = raw;
  if (typeof raw === "string") {
    const trimmed = raw.trim();
    if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
      try {
        data = JSON.parse(trimmed);
      } catch {
        return { summary: trimmed };
      }
    } else {
      return { summary: trimmed };
    }
  }
  if (typeof data !== "object") return { summary: String(data) };
  if (data.output) return normalize(data.output);
  if (data.contentJson) return normalize(data.contentJson);
  // unwrap if backend returned { result: {...} } or { data: {...} }
  if (data.result && typeof data.result === "object") data = data.result;
  if (data.data && typeof data.data === "object") data = data.data;
  return {
    summary: data.summary || data.text || data.message || "",
    recommendations: data.recommendations || data.suggestions || [],
    tasks: data.tasks || data.suggestedTasks || [],
    insights: data.insights || data.analysis || [],
    warnings: data.warnings || data.notes || [],
  };
}

function Section({ icon: Icon, title, items, accent }) {
  if (!items || items.length === 0) return null;
  return (
    <div className="ai-section">
      <div className={`ai-section-head ${accent || ""}`}>
        <Icon size={14} /> <span>{title}</span>
      </div>
      <ul className="ai-list">
        {items.map((it, i) => (
          <li key={i}>{typeof it === "string" ? it : it.title || JSON.stringify(it)}</li>
        ))}
      </ul>
    </div>
  );
}

export default function AIOutputCard({ data, title = "AI Insight" }) {
  const norm = normalize(data);
  if (!norm) return null;

  return (
    <div className="ai-card">
      <div className="ai-head">
        <div className="ai-icon">
          <Sparkles size={16} />
        </div>
        <div>
          <div className="ai-title">{title}</div>
          <div className="ai-sub">Generated by your AI assistant</div>
        </div>
      </div>

      {norm.summary && <p className="ai-summary">{norm.summary}</p>}

      <Section icon={Lightbulb} title="Recommendations" items={norm.recommendations} accent="g" />
      <Section icon={ListChecks} title="Suggested tasks" items={norm.tasks} accent="b" />
      <Section icon={BookOpen} title="Insights" items={norm.insights} accent="g" />
      <Section icon={AlertTriangle} title="Notes" items={norm.warnings} accent="w" />
    </div>
  );
}
