import { Sparkles, Lightbulb, ListChecks, AlertTriangle, BookOpen } from "lucide-react";

function mergeMeta(outer, inner) {
  if (!inner) return inner;
  const fallback = outer.source === "local-fallback" || inner.fallback;
  return {
    ...inner,
    provider: outer.provider || inner.provider,
    model: outer.model || inner.model,
    live: outer.live === true || inner.live,
    fallback,
  };
}

function normalize(raw) {
  if (!raw) return null;
  let data = raw;
  if (typeof raw === "string") {
    const trimmed = raw.trim();
    if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
      try {
        data = JSON.parse(trimmed);
      } catch {
        return { summary: trimmed };
      }
    } else {
      return { summary: trimmed };
    }
  }
  if (typeof data !== "object") return { summary: String(data) };
  if (data.output) {
    const inner = normalize(data.output);
    return mergeMeta(data, inner);
  }
  if (data.contentJson) {
    const inner = normalize(data.contentJson);
    return mergeMeta(data, inner);
  }
  if (data.result && typeof data.result === "object") data = data.result;
  if (data.data && typeof data.data === "object") data = data.data;
  const fallback = data.source === "local-fallback"
    || (typeof data.summary === "string" && data.summary.includes("Local AI fallback"));
  return {
    summary: data.summary || data.text || data.message || "",
    recommendations: data.recommendations || data.suggestions || [],
    tasks: data.tasks || data.suggestedTasks || [],
    insights: data.insights || data.analysis || [],
    warnings: data.warnings || data.notes || [],
    provider: data.provider || "",
    model: data.model || "",
    live: data.live === true || data.source === "ai",
    fallback,
  };
}

function humanizeSummary(text) {
  return String(text || "")
    .replace(/\b[Bb]ased on the user's\b/g, "Looking at your")
    .replace(/\b[Bb]ased on the user data\b/g, "Looking at your recent logs")
    .replace(/\bthe user's\b/g, "your")
    .replace(/\b[Tt]he user\b/g, "you")
    .replace(/\b[Tt]he system suggests\b/g, "A useful next step is")
    .replace(/\b[Tt]he system recommends\b/g, "A useful next step is");
}

function Section({ icon: Icon, title, items, accent }) {
  if (!items || items.length === 0) return null;
  return (
    <div className="ai-section">
      <div className={`ai-section-head ${accent || ""}`}>
        <Icon size={14} /> <span>{title}</span>
      </div>
      <ul className="ai-list">
        {items.map((it, i) => (
          <li key={i}>{typeof it === "string" ? it : it.title || JSON.stringify(it)}</li>
        ))}
      </ul>
    </div>
  );
}

export default function AIOutputCard({ data, title = "AI Insight", simple = false, hideMeta = false }) {
  const norm = normalize(data);
  if (!norm) return null;

  return (
    <div className="ai-card">
      <div className="ai-head">
        <div className="ai-icon">
          <Sparkles size={16} />
        </div>
        <div>
          <div className="ai-title">{title}</div>
          {!hideMeta && <div className="ai-sub">
            {norm.fallback
              ? "Local fallback (no live API key or provider error)"
              : norm.provider && norm.model
                ? `Live AI · ${norm.provider} / ${norm.model}`
                : "Generated by your AI assistant"}
          </div>}
        </div>
      </div>

      {norm.summary && <p className="ai-summary">{humanizeSummary(norm.summary)}</p>}

      {!simple && (
        <>
          <Section icon={Lightbulb} title="Recommendations" items={norm.recommendations} accent="g" />
          <Section icon={ListChecks} title="Suggested tasks" items={norm.tasks} accent="b" />
          <Section icon={BookOpen} title="Insights" items={norm.insights} accent="g" />
          <Section icon={AlertTriangle} title="Notes" items={norm.warnings} accent="w" />
        </>
      )}
    </div>
  );
}
